### ISSUE TITLE
Attributes not coerced when persisted

### ISSUE THREAD

**Issue by angeloashmore** [lotus/model#138]
```ruby
class User
  include Lotus::Entity
  attributes :id, :name, :age
end

mapper = Lotus::Model::Mapper.new do
  collection :users do
    entity User

    attribute :id,   String
    attribute :name, String
    attribute :age,  Integer
  end
end.load!

user1 = User.new(name: 'Luca', age: '32')
UserRepository.persist(user1)
```

When `user1` is persisted, the age is **not** coerced to an `Integer` before persisting and remains as a string. For dynamic datastores (e.g. RethinkDB), the type is kept intact.

When retrieved from storage, `user1.age` is coerced to an `Integer` from a `String`.

Is this behavior intended? I can see how input should be type-validated before it reaches the persisting method, but defining the type in the mapper should guarantee the type is saved properly.

Is it the job of the adapter to coerce the attributes?

**Comment by AlfonsoUceda** [comment]
IMHO I think should be coerced before and after, maybe if we coerce the value before, after it doesn't make sense and so the correct value coerced is stored in the database (or another system) with the correct type

**Comment by joneslee85** [comment]
The coercion is the job of the Repository. After the repository persist the entity, it does not refresh the entity thus you might see the entity's values are not coerced.

 If you look into the DB, the stored values are coerced. And when you use Repository to find the entity, this time the entity values would reflect correctly.

I think it is a good idea to refresh the states of the entity after successful persist operation. Thoughts?

**Comment by joneslee85** [comment]
@angeloashmore I'll have further discussion with @jodosha as I try to avoid additional calls. Thanks for reporting.

**Comment by jodosha** [comment]
@angeloashmore What's your use case? Is that database shared from with other services that need a stricter type check on data?

Until know, `#to_record` doesn't coerce because that information about the Ruby type can be lost while writing on certain databases.

Think of Redis:

```ruby
[1] pry(main)> require 'redis'
=> true
[2] pry(main)> r = Redis.new
=> #<Redis client v3.2.0 for redis://127.0.0.1:6379/0>
[3] pry(main)> r.set('x', Integer("1"))
=> "OK"
```

```shell
% redis-cli
127.0.0.1:6379> get x
"1"
```

We coerced our input from `String` (`"1"`) to `Integer` and then persisted it. Later on, if we introspect the value stored by database, it's a string. Our coercion get lost, because the database doesn't support that type.

From a Lotus::Model perspective, it should guarantee that a value fetched from the database will be coerced into the mapped Ruby type.

It's true, we're lucky enough in SQL world, where database engines will anyway coerce that value into an integer because we have types in schema definitions.

On the other hand, I'm not easy to add a computation overhead for the most common scenarios that don't need it.

**What to do then?**

**Option 1**
There is an extension point for adapters when they explicitly ask for database conversion. `Sql::Collection` is an example: it has a `@mapped_collection` which is an instance of `Mapping::Collection`. It's an object that holds the mapping definitions for that collection.

When it needs to create a record, it asks to the `@mapped_collection` to serialize it. But you can do the opposite:

```ruby
private
def _serialize(entity)
  MyCoercer.new(entity).coerce
end
```

**Option 2**
Add another setting in `Model::Configuration` to specify a coercer object to pass when the mapper is instantiated. @joneslee85 thoughts on this option?

**Comment by jodosha** [comment]
@angeloashmore There is a different issue about the returned entity from a `BookRepository.create` operation, and I agree with you: it should return the coerced entity.

```ruby
book = BookRepository.create(Book.new(price: '10'))
book.price # => "10" WRONG, it should be an integer.
```

This can be easily fixed.

**Comment by angeloashmore** [comment]
@jodosha @joneslee85 In my opinion, attributes should be coerced via the mapper before persisting. Is this what you mean with Option 2?

This would allow the adapter and database library to handle any entity/database type differences.

In your Redis example, the Redis library accepted an `Integer` despite not handling `Integer` as a type. The library automatically saved a `String` instead. Let's say in the future the user changes the adapter, for example to RethinkDB. This new database accepts `Integers` and thus will keep the type.

**Persisting to the database**

1. Call `Repository#persist`
2. Repository coerces attributes using the mapper before persisting.
3. Repository persists the entity to the database with the coerced values.

**Retrieving from the database**

1. Call `Repository#find`
2. Repository gets the database record/document and coerces attributes using the mapper.

This ensures the following:

* Adapter recieves all attributes with the correct, expected types
* Adapter or DB library handles any type changes if necessary (e.g. unsupported types)
* Database methods can run queries in an expected way (e.g. we can now assume `:age` will always be an `Integer` in the DB, so we can run `#sum`)
* Retriving using the Repository always returns the correct types

---

I noticed the issue when running math functions (e.g. #sum, #avg, #max, #min) directly on the database via a Collection object.

The repository was persisting Strings and Integers for the same attribute depending on how the entity was initiated, so the database could not compute the equation due to the type mismatch.

```ruby
  # raises error if type mismatch on `age` field
  query do
    where { |u| u[:age] > 10 }
  end.sum(:age)
```

If the database can save arbitrary types and values are only coerced upon deserialization, the equation would need to be computed via Ruby after retrieving all values of the attribute. I would imagine this would be slower (just a guess; I have not actually tested the performance).

**Comment by jodosha** [comment]
@angeloashmore I was wrong, you were right.

I've replied without having the code around, so my thinking was biased by the initial design.
I've put in place coercion before persistence to avoid to hit the database to reload the record.

Can you please give #141 a try and see if it solves your problems? Because this is a blocking issue, once I get your and @joneslee85 go, I'm keen to release a patch version for this.

**Comment by angeloashmore** [comment]
@jodosha Sorry for the late reply. Just had a chance to test it out. Everything looks good! :+1:

**Comment by jodosha** [comment]
@angeloashmore No worries, expect a patch release soon.

**Comment by jodosha** [comment]
@angeloashmore https://rubygems.org/gems/lotus-model/versions/0.2.2
