### ISSUE TITLE
Array Coercion makes a 'record' not a text[] in pg

### ISSUE THREAD

**Issue by peterberkenbosch** [lotus/model#183]
Using postgresql and lotus model from the master branch. I would like to store an array of Strings in an entity like this:

```ruby
attribute :images, type: Array
```
Then migrate the database with this:
```ruby
add_column :products, :images, "text[]"
```

I verified that the database was migrated correctly. 

When I try to run the specs storing an array of images like this:

```ruby
images: [
          "http://dummyimage.com/600x400/000/fff&text=1",
          "http://dummyimage.com/600x400/000/fff&text=2",
          "http://dummyimage.com/600x400/000/fff&text=3"
        ]
```

I get this error from Sequel:

```
Sequel::DatabaseError:
       PG::DatatypeMismatch: ERROR:  column "images" is of type text[] but expression is of type record
       LINE 1: ....814681+0000', '2015-05-04 10:08:00.814681+0000', ('http://d...
                                                                    ^
       HINT:  You will need to rewrite or cast the expression.
```

I would love follow that HINT, and I will try to. Not 100% sure if this is something in Lotus currently of just me using the attributes in a wrong way.

**Comment by jodosha** [comment]
@peterberkenbosch I have looked at this issue several times, trying to find a quick solution, but it isn't the case. This is the reason of this late reply. I'm sorry about this.

Our serialization strategy right now tries to be adapter independent: one code for all the database types, file system and SQL. This design works fine when you have basic data types (string, integer), because they are understood by all the databases.

You hit a limitation of this approach because of PG array, which is a very specific data type. The coercer returns a Ruby Array, which is sent straight to Sequel, then to the database, without worrying about the underlying database schema for that column.

I'm afraid we should postpone the fix for this.

My idea is to have a `:coercer` option for the mapper.

```ruby
require 'sequel/extensions/pg_array'

collection :products do
  # ...
  attribute :images, Array, coercer: ->(value) { Sequel.pg_array(value) }
end
```

/cc @joneslee85
