### ISSUE TITLE
Issues with memory adapter when id column is mapped as a string

### ISSUE THREAD

**Issue by taylorfinnell** [lotus/model#202]
Repo.find does not seem to function. I believe it is because the `PrimaryKey` class in `Memory::Collection`always use an integer.

For some adapters, like a rest adapter, an `id` might only be expressible as a string, `MemoryAdapter` not handling string integers creates different behavior between adapters. I force all repositories to be use the `MemoryAdapter` in tests for faster tests, so it is important for adapters to behave the same way.

Thanks for any info on the issue

**Comment by joneslee85** [comment]
@taylorfinnell thanks for the bug report, would you be able to write me a failed spec for my investigation?

**Comment by taylorfinnell** [comment]
I'll try to get something in next day-ish. I think changing the `Integer` to `String` in this test test/model/adapters/memory_adapter_test.rb:25 will re-produce the error. I will try to get a real failing spec soon-ish :).

**Comment by mjbellantoni** [comment]
@joneslee85 does this mean the memory adapter should be enhanced to support non-integer primary keys?

**Comment by taylorfinnell** [comment]
Here is a failing test for the memory adapter

```
describe 'typed primary keys' do
    before do
      @mapper = Lotus::Model::Mapper.new do
        collection :users do
          entity TestUser
          attribute :id, String
        end
      end.load!

      @adapter = Lotus::Model::Adapters::MemoryAdapter.new(@mapper)
    end

    it 'can find an entity by a non integer primary key' do
      user = @adapter.create(:users, TestUser.new)

      @adapter.find(collection, user.id).must_equal(user)
    end
  end
```
If you change the String mapping to Integer the test passes with no other changes. I was looking into extending `PrimaryKey` but after a quick was not sure how I could access the coercer.

**Comment by jodosha** [comment]
@taylorfinnell Hello and thanks for reporting your problem :smile: 

Memory/FileSystem adapters are toys that allow you rapid prototyping when you create a new app. Once you get into the phase where a real db is needed, you should stick with it. For instance, if you choose Postgres, you should use it in dev/testing/staging/production. Parity between environments is **really** valuable.

Don't trade speed of memory with stability of your software. Lotus' modularity helps you to avoid to hit the database when not needed, but when you're testing your model layer, you should use the database that will be deployed in production. A good read about this topic can be found here: http://12factor.net/dev-prod-parity

These are the founding principles for Lotus::Model and its adapters.
Memory/FS can't be a replacement for all the databases that you may want to use. Otherwise they should support, k/v, SQL, document database, plus JOINS, nested values, map/reduce, which is too much IMO.

They just mimic a naive SQL, because it's the simplest thing to do. The assumption is to have an autoincrement integer primary key.

I'm for keeping them simple, as they are a toy. :tractor: 

Now that we have narrowed the problem, the question is simple: how we can help you with your adapter? Is there anything that I'm missing? I'm always open to suggestions. Thank you very much. :+1:

**Comment by taylorfinnell** [comment]
I understand your points, thank you for the response. The adapter I need really only must implement #find and potentially #create. It reaches out to an HTTP endpoint for users. Since all adapters implemented #find and #create behave the same way it seemed reasonable to swap out adapters in the test environment instead of waiting for dummy users to be created, and http requests to fire etc etc. However, I can also see the value in using that adapter in test to get dev and production more similar. Something for me to think about! Thank you!

**Comment by jodosha** [comment]
@taylorfinnell Sure, happy to be helpful here. I'd suggest to use [webmock](https://github.com/bblimke/webmock) to avoid to hit the external service during your tests.

I'm closing this. Thank you. :+1:
