### ISSUE TITLE
Any particular reason why Repository works with class methods?

### ISSUE THREAD

**Issue by mjacobus** [lotus/model#240]
Hey guys.

I was wondering ever since I started reading the manual and playing a bit with lotus why repository is not a object. To me it would make more sense to instantiate the repo passing the adapter as argument in the constructor.

Sorry if this is not the correct to ask that.

Cheers!

**Comment by jodosha** [comment]
@mjacobus Hello, you are encouraged to ask questions at any time :)

The initial design was influenced by a few factors. Firstly, it's a common pattern in Ruby libs to use classes for repositories (eg, ActiveRecord and Sequel Model CRUD methods). As second reason, It's a bit cumbersome to instantiate it and give the adapter as argument, because that means to pass the adapter around..

```ruby
BookRepository.new(adapter) # where adapter comes from?
```

To fix this, we can do:

```ruby
module Lotus::Repository
  def initialize
    @adapter = self.class.adapter
  end
end
```

But there is one last thing to take into account for now. Each adapter exposes its own API, so if you use a third part Redis adapter, you won't be able to use `join`, while that is possible with the SQL one.

Adapters are equivalent, but once you committed to one, you can't easily interchange them. I wanted discourage to pass them as a dependency for this reason.

```ruby
class BookRepository
  include Lotus::Repository

  def self.foo
    query do
      get "foo" # uses Redis adapter
    end
  end
end
```

In the example above, you can't configure the SQL adapter, because it doesn't respond to `#get` and it will crash.

That being said, I'm tempted to overcome to those limitations and make them to work as objects, not as classes.

I hope this is clear now. Thoughts?

/cc @solnic

**Comment by mjacobus** [comment]
Thank you very much for your response, @jodosha =)

Yes, I understand that some adapters would expose some methods that others can't.
I think the adapter could come from a factory, and that most users could just not care about that.

Perhaps something like:

```ruby
books = ApplicationDependencies.get(BookRepository)
```

What a personally do not like is that the Repo is then a kind of global variable. In the above example ApplicationDependencies is global, but more or less OK.

Perhaps in the place the controllers are created, the ApplicationDependencies could be injected.

```ruby
# the place where action is created
def method_that_creates_action
  ## original code above
  dependency_manager = ApplicationDependencies.create
  action.dependency_manager = dependency_manager
  action
end
```

```ruby
module Web::Controllers::Dashboard
  class Index
    include Web::Action

    def call(params)
      books = dependency_manager.get(BookRepository)
      ## do something
    end
  end
end
```

Well, but this is probably just opinion... =)

**Comment by solnic** [comment]
(here I go again ;)) Most *common* patterns in Ruby are flawed. Class-interface-oriented design is one of them. For me classes are great as object factories, nothing more. Objects are nicer because you need to treat them explicitly as dependencies and they are easier to compose as opposed to class constants because they are not as flexible as objects. Given that we managed to build ROM in a way where *everything* is an object, I'm pretty sure there are no cases where having an object would be a blocker for some functionality. It's a matter of coming up with an interface design that can work with objects only.

In example in rom-repository repositories are now instantiated with a whole ROM container as they grab specific components from that container to set themselves up, and it's not nice. So my plan is to come up with a separate setup interface for repository classes where a specific class would be configured in a way that it will know how to build its instance using configured container. So, at the end of the day, a repository would be instantiated by passing its dependencies to the constructor, so rather than having the constructor know how to instantiate repository dependencies, it would simply receive them and set as ivars.

FWIW I don't think that passing adapter as a dependency would be a design smell, after all it *is* a dependency of a repository. ie in ROM a relation object receives a dataset object as its dependency and it decorates the dataset by wrapping its responses. Notice that the dataset is the actual interface that talks to a specific database, furthermore it varies across different ROM adapters, so pretty similar situation as in lotus-model repository. I don't see it as a problem. Relations are instantiated by ROM during the setup phase, you don't have control here unless you want to instantiate relations yourself, and in that case you probably know what you're doing (and why) so it's fine.

This consistency is quite beautiful, I've been doing that not just in libraries but everywhere and I never looked back. Recently I finally found a simple IoC [solution](https://github.com/dryrb/dry-container) and started using it for every-single-dependency-that-exists-in-my-systems and it's an absolutely fantastic experience. I loved it so much that I wrote an [auto-injection lib](https://github.com/dryrb/dry-auto_inject) to work with it nicely and remove the nasty boilerplate code from my classes and it's been literally an epiphany for me. Once every object in your system is easily accessible via container your life becomes so much simpler. I'm not going to mention testability, because that's just a sweet side-effect.

Now, with classes, you can't do that, because classes are not a composition of objects, they are globals, often mutable, their dependencies are often hidden through various implicit behavior, you can't control them as easily as you can in case of objects.

**Comment by mjacobus** [comment]
Hi @jodosha

Finally I got the time to work an example for what I meant. And I believe it is inline with what @solnic mentioned.

Here is an example how the repository can be created with its dependencies and easily used inside the application. That is a WIP and it is an app that I want to build.

- [Application dependencies](https://github.com/mjacobus/quizzy/blob/feature-quiz/lib/application/dependencies.rb)
- [Action](https://github.com/mjacobus/quizzy/blob/feature-quiz/apps/admin/controllers/quizzes/index.rb)
- [Repository](https://github.com/mjacobus/quizzy/blob/feature-quiz/lib/quizzy/repositories/quiz_repository.rb)
- [Entity](https://github.com/mjacobus/quizzy/blob/feature-quiz/lib/quizzy/entities/quiz.rb)

Here are the gems I used for:

- [Repository](https://github.com/mjacobus/koine-repository)
- [Dependency Injection](https://github.com/mjacobus/nurse-rb)

I think some kind of dependency injection is a very nice to have in lotus. It solves the "D" part int he SOLID principle. It encourages changing behavior by composability rather then inheritance. Also it improves testability. In this example the repo can be tested by mocking the adapter instead of hitting the db, although for most cases I would prefer the latter.

Notice that I created a ```lib/application``` directory. There is where I want to store the application specific stuff, such as database setup and so forth.

As for the application business logic, I want it to live inside ```lib/quizzy```. Later I will introduce some kind of service layer to be used inside of the actions, so the buisness logic wont liq into the controllers/actions. Also, if I want, I can gemified it, and if I want I can "easily" switch the application to rails, or to any other framework.

If you think factories and dependency injection can be interesting for lotus I can work in a concept and create a PR.

Cheers!
